import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { GenerationConfig } from "../types";

export class GeminiService {
  /**
   * Always create a new instance right before making an API call to ensure it always uses the most up-to-date API key.
   */
  private static getAI() {
    return new GoogleGenAI({ apiKey: process.env.API_KEY as string });
  }

  static async generateImage(config: GenerationConfig, referenceImage?: string) {
    const ai = this.getAI();
    // gemini-3-pro-image-preview is mandatory for high-quality and search-enabled tasks.
    const modelName = 'gemini-3-pro-image-preview';

    const parts: any[] = [{ text: config.prompt }];
    
    if (config.negativePrompt) {
      parts.push({ text: `Avoid generating these elements: ${config.negativePrompt}` });
    }

    if (referenceImage) {
      const base64Data = referenceImage.split(',')[1];
      const mimeType = referenceImage.match(/data:(.*?);/)?.[1] || 'image/png';
      parts.push({
        inlineData: {
          data: base64Data,
          mimeType: mimeType
        }
      });
    }

    const response = await ai.models.generateContent({
      model: modelName,
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: config.aspectRatio,
          imageSize: config.imageSize
        }
      }
    });

    let imageUrl = '';
    // Find the image part, do not assume it is the first part.
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) throw new Error("No image was generated by the model.");
    return imageUrl;
  }
}